<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2025-06-05 11:17:02                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class UserWatchedThreadsDAO extends OneToManyLinked
	{
		public function __construct(User $user, $lazy = false)
		{
			parent::__construct(
				$user,
				WatchedThread::dao(),
				$lazy
			);
		}
		
		/**
		 * @return UserWatchedThreadsDAO
		**/
		public static function create(User $user, $lazy = false)
		{
			return new self($user, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'user_id';
		}
		
		public function makeQuery() 
		{
      /** @var UnifiedContainerWorker $worker */
      $worker = $this->worker;
      return $worker->makeFetchQuery();
    }
	}
?>
