apiVersion: apps/v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ .Chart.Name }}
    namespace: {{ .Values.namespace }}
  spec:
    replicas: {{ .Values.replicaCount }}
    selector:
      matchLabels:
        app: {{ .Chart.Name }}
    template:
      metadata:
        labels:
          app: {{ .Chart.Name }}
      spec:
        restartPolicy: {{ .Values.restartPolicy }} 
        containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: TORGATE_HOSTNAME
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.torgateHostname }}
                name: {{ .Values.nullSecrets.name }}
          - name: TORGATE_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.torgatePublicKey }}
                name: {{ .Values.nullSecrets.name }}
          - name: TORGATE_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.torgatePrivateKey }}
                name: {{ .Values.nullSecrets.name }}
          - name: TORGATE_ENDPOINT
            value: "frontend:80"

kind: List
metadata: {}
