apiVersion: apps/v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ .Values.svc.cache.name }}
    namespace: {{ .Release.Namespace }}
  spec:
    replicas: {{ .Values.svc.cache.image.replicas }}
    selector:
      matchLabels:
        app: {{ .Values.svc.cache.name }}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: {{ .Values.svc.cache.name }}
      spec:
        hostname: {{ .Values.svc.cache.name }}
        restartPolicy: {{ .Values.restartPolicy }} 
        containers:
        - name: {{ .Values.svc.cache.image.name }}
          image: {{ .Values.svc.cache.image.name }}:"{{ .Values.svc.cache.image.tag }}"
          imagePullPolicy: {{ .Values.svc.cache.image.pullPolicy }}
          ports:
          - containerPort: 6379

- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Values.svc.cache.name }}
    namespace: {{ .Release.Namespace }}
  spec:
    selector:
      app: {{ .Values.svc.cache.name }}
    clusterIP: None

kind: List
metadata: {}
