apiVersion: apps/v1
items:

- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: {{ .Values.svc.db.name }}
    namespace: {{ .Release.Namespace }}
  spec:
    replicas: {{ .Values.svc.db.image.replicas }}
    serviceName: "{{ .Values.svc.db.name }}"
    minReadySeconds: 10
    selector:
      matchLabels:
        app: {{ .Values.svc.db.name }}
    template:
      metadata:
        labels:
          app: {{ .Values.svc.db.name }}
          part-of: lb
      spec:
        hostname: {{ .Values.svc.db.name }}
        restartPolicy: {{ .Values.restartPolicy }} 
        terminationGracePeriodSeconds: 30
        securityContext:
          runAsUser: 70
          fsGroup: 70
        containers:
        - name: {{ .Values.svc.db.image.name }}
          image: {{ .Values.svc.db.image.name }}:"{{ .Values.svc.db.image.tag }}"
          imagePullPolicy: {{ .Values.svc.db.image.pullPolicy }}
          ports:
          - containerPort: 5432
            protocol: TCP
          env:
          - name: PGDATA
            value: "/var/lib/postgresql/data/pgdata"
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                key: POSTGRES_DB
                name: {{ include "SecretsName" . }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: {{ include "SecretsName" . }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: {{ include "SecretsName" . }}
          volumeMounts:
          - name: {{ .Values.svc.db.name }}-pv
            mountPath: /var/lib/postgresql/data
    volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-{{ .Values.svc.db.name }}-pv
      spec:
        accessModes: [ {{ .Values.storageClass.accessMode }} ]
        storageClassName: {{ include "StorageClassName" . }}
        resources:
          requests:
            storage: {{ include "DbSpace" . }}
        volumeMode: Filesystem
            
- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Values.svc.db.name }}
    namespace: {{ .Release.Namespace }}
  spec:
    selector:
      app: {{ .Values.svc.db.name }}
    clusterIP: None

kind: List
metadata: {}
