apiVersion: apps/v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ .Values.svc.torgate.name }}
    namespace: {{ .Release.Namespace }}
  spec:
    replicas: {{ .Values.svc.torgate.image.replicas }}
    selector:
      matchLabels:
        app: {{ .Values.svc.torgate.name }}
    template:
      metadata:
        labels:
          app: {{ .Values.svc.torgate.name }}
      spec:
        restartPolicy: {{ .Values.restartPolicy }}
        {{ include "ImagePullSecret" . }}
        containers:
        - name: {{ .Values.svc.torgate.image.name }}
          image: {{ include "ImageRegistry" . }}/{{ .Values.svc.torgate.image.name }}:"{{ .Values.svc.torgate.image.tag }}"
          imagePullPolicy: {{ .Values.svc.torgate.image.pullPolicy }}
          env:
          - name: TORGATE_HOSTNAME
            valueFrom:
              secretKeyRef:
                key: TORGATE_HOSTNAME
                name: {{ include "SecretsName" . }}
          - name: TORGATE_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                key: TORGATE_PUBLIC_KEY
                name: {{ include "SecretsName" . }}
          - name: TORGATE_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: TORGATE_PRIVATE_KEY
                name: {{ include "SecretsName" . }}
          - name: GATE_ENDPOINT_HOST
            valueFrom:
              secretKeyRef:
                key: GATE_ENDPOINT_HOST
                name: {{ include "SecretsName" . }}
          - name: GATE_ENDPOINT_PORT
            valueFrom:
              secretKeyRef:
                key: GATE_ENDPOINT_PORT
                name: {{ include "SecretsName" . }}

kind: List
metadata: {}
