apiVersion: apps/v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ .Chart.Name }}
    namespace: {{ .Values.namespace }}
  spec:
    replicas: {{ .Values.replicaCount }}
    selector:
      matchLabels:
        app: {{ .Chart.Name }}
    template:
      metadata:
        labels:
          app: {{ .Chart.Name }}
      spec:
        restartPolicy: {{ .Values.restartPolicy }} 
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
          sysctls:
          - name: net.ipv6.conf.all.disable_ipv6
            value: "0"
        containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: YGGDRASILGATE_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.yggdrasilgatePrivateKey }}
                name: {{ .Values.nullSecrets.name }}
          - name: GATE_ENDPOINT_HOST
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.gateEndpointHost }}
                name: {{ .Values.nullSecrets.name }}
          - name: GATE_ENDPOINT_PORT
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.gateEndpointPort }}
                name: {{ .Values.nullSecrets.name }}
          volumeMounts:
          - mountPath: /dev/net/tun
            name: tun
        volumes:
        - name: tun
          hostPath:
            path: /dev/net/tun

kind: List
metadata: {}
