<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2025-09-23 21:23:44                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoStorageTrash extends IdentifiableObject
	{
		protected $filename = null;
		
		public function getFilename()
		{
			return $this->filename;
		}
		
		/**
		 * @return StorageTrash
		**/
		public function setFilename($filename)
		{
			$this->filename = $filename;
			
			return $this;
		}
	}
?>