project: "0chan"
version: "0.1.0"

repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets

.options: &options
  namespace: nullchan
  wait: true
  max_history: 3

releases:

  - name: frontend
    <<: *options
    chart: charts/frontend
    values:
    - src: values.yaml
    tags:
      - deploy
    depends_on:
      - charts/backend
      - charts/storage
      - charts/tools

  - name: backend
    <<: *options
    chart: charts/backend
    values:
    - src: values.yaml
    tags:
      - deploy
    depends_on:
      - charts/db
      - charts/cache

  - name: storage
    <<: *options
    chart: charts/storage
    values:
    - src: values.yaml
    tags:
      - deploy

  - name: db
    <<: *options
    chart: charts/db
    values:
    - src: values.yaml
    tags:
      - deploy

  - name: cache
    <<: *options
    chart: charts/cache
    values:
    - src: values.yaml
    tags:
      - deploy

  - name: torgate
    <<: *options
    chart: charts/torgate
    values:
    - src: values.yaml
    tags:
      - deploy
    depends_on:
      - charts/frontend

  - name: sealed-secrets
    namespace: kube-system
    chart: sealed-secrets/sealed-secrets
    tags:
      - setup

  - name: csi-s3
    namespace: kube-system
    chart: charts/csi-s3
    values:
    - src: .keys.yaml
    tags:
      - setup

  - name: tools
    namespace: nullchan
    chart: charts/tools
    values:
    - values.yaml
    - .env.yaml
    lifecycle:
      pre_up:
        - bash config/sealEnv.sh
    tags:
      - setup
    depends_on:
      - sealed-secrets/sealed-secrets
