namespace: nullchan
restartPolicy: Always
  
nullSecrets:
  name: nullchan-secrets
  envName:
    admingLogin: ADMIN_LOGIN
    adminPasswd: ADMIN_PASSWD
    salt: SALT
    storageId: STORAGE_ID
    postgresDb: POSTGRES_DB
    postgresUser: POSTGRES_USER
    postgresPasswd: POSTGRES_PASSWORD
    torgateHostname: TORGATE_HOSTNAME
    torgatePublicKey: TORGATE_PUBLIC_KEY
    torgatePrivateKey: TORGATE_PRIVATE_KEY
    
storageClass:
  local:
    name: "nullchan-ssd"
    accessMode: "ReadWriteOnce"
    pods:
      storage:
        requestSpace: 20Gi
      db:
        requestSpace: 5Gi
  yc:
    name: "csi-s3"
    accessMode: ReadWriteMany
    requestSpace: 1Gi
