namespace: nullchan
restartPolicy: Always
  
nullSecrets:
  name: nullchan-secrets
  envName:
    admingLogin: ADMIN_LOGIN
    adminPasswd: ADMIN_PASSWD
    salt: SALT
    storageId: STORAGE_ID
    postgresDb: POSTGRES_DB
    postgresUser: POSTGRES_USER
    postgresPasswd: POSTGRES_PASSWORD
    gateEndpointHost: GATE_ENDPOINT_HOST
    gateEndpointPort: GATE_ENDPOINT_PORT
    torgateHostname: TORGATE_HOSTNAME
    torgatePublicKey: TORGATE_PUBLIC_KEY
    torgatePrivateKey: TORGATE_PRIVATE_KEY
    i2pgatePrivateKey: I2PGATE_PRIVATE_KEY
    yggdrasilgatePrivateKey: YGGDRASILGATE_PRIVATE_KEY
    
image:
  repository: ghcr.io/katzterd/0chan
    
storageClass:
  name: "0chan-default-sc"
  accessMode: "ReadWriteOnce"
  pods:
    storage:
      requestSpace: 20Gi
    db:
      requestSpace: 5Gi
