apiVersion: apps/v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ .Chart.Name }}
    namespace: {{ .Values.namespace }}
  spec:
    replicas: {{ .Values.replicaCount }}
    selector:
      matchLabels:
        app: {{ .Chart.Name }}
    template:
      metadata:
        labels:
          app: {{ .Chart.Name }}
      spec:
        restartPolicy: {{ .Values.restartPolicy }} 
        containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: I2PGATE_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.i2pgatePrivateKey }}
                name: {{ .Values.nullSecrets.name }}
          - name: GATE_ENDPOINT_HOST
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.gateEndpointHost }}
                name: {{ .Values.nullSecrets.name }}
          - name: GATE_ENDPOINT_PORT
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.gateEndpointPort }}
                name: {{ .Values.nullSecrets.name }}

kind: List
metadata: {}
