apiVersion: v1
kind: Service
metadata:
  name: frontend-0chan-expose
  namespace: nullchan-dev
spec:
  ports:
  - name: frontend
    port: 80
    targetPort: 80
  externalTrafficPolicy: Local
  selector:
    part-of: lb
  type: LoadBalancer
