apiVersion: v1
kind: Service
metadata:
  name: db-0chan-expose
  namespace: nullchan
spec:
  ports:
  - name: db
    port: 5432
    targetPort: 5432
  externalTrafficPolicy: Local
  selector:
    part-of: lb
  type: LoadBalancer
