apiVersion: apps/v1
items:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: {{ .Chart.Name }}
    namespace: {{ .Values.namespace }}
  spec:
    replicas: {{ .Values.replicaCount }}
    selector:
      matchLabels:
        app: {{ .Chart.Name }}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
    template:
      metadata:
        labels:
          app: {{ .Chart.Name }}
      spec:
        hostname: {{ .Chart.Name }}
        restartPolicy: {{ .Values.restartPolicy }} 
        containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 9000
          env:
          - name: ADMIN_LOGIN
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.admingLogin }}
                name: {{ .Values.nullSecrets.name }}
                optional: true
          - name: ADMIN_PASSWD
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.adminPasswd }}
                name: {{ .Values.nullSecrets.name }}
                optional: true
          - name: SALT
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.salt }}
                name: {{ .Values.nullSecrets.name }}
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.postgresDb }}
                name: {{ .Values.nullSecrets.name }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.postgresUser }}
                name: {{ .Values.nullSecrets.name }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: {{ .Values.nullSecrets.envName.postgresPasswd }}
                name: {{ .Values.nullSecrets.name }}
              
- apiVersion: v1
  kind: Service
  metadata:
    name: {{ .Chart.Name }}
    namespace: {{ .Values.namespace }}
  spec:
    selector:
      app: {{ .Chart.Name }}
    clusterIP: None

kind: List
metadata: {}
