apiVersion: apps/v1
items:

#- apiVersion: v1
#  kind: Namespace
#  metadata:
#    labels:
#      kubernetes.io/metadata.name: {{ .Values.namespace }}
#    name: {{ .Values.namespace }}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-images
    namespace: {{ .Values.namespace }}
  spec:
    storageClassName: {{ .Values.storageClass.yc.name }}
    accessModes:
    - {{ .Values.storageClass.yc.accessMode }}
    resources:
      requests:
        storage: {{ .Values.storageClass.yc.requestSpace }}

- apiVersion: v1
  kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: {{ .Values.storageClass.local.name }}
  provisioner: disk-csi-driver.mks.ycloud.io
  volumeBindingMode: WaitForFirstConsumer
  parameters:
    type: network-ssd
    csi.storage.k8s.io/fstype: ext4
  allowVolumeExpansion: true
  reclaimPolicy: Retain


- apiVersion: v1
  kind: Service
  metadata:
    name: frontend-lb
    namespace: {{ .Values.namespace }}
  spec:
    ports:
    - port: 80
      targetPort: 80
    externalTrafficPolicy: Cluster
    selector:
      app: frontend
    type: LoadBalancer
    
- apiVersion: v1
  kind: Service
  metadata:
    name: postgres-lb
    namespace: {{ .Values.namespace }}
    labels:
      app: postgres
  spec:
    ports:
    - port: 5432
      targetPort: 5432
    externalTrafficPolicy: Cluster
    selector:
      app: db
    type: LoadBalancer

kind: List
metadata: {}
