<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2025-06-05 10:52:30                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoWatchedThread extends AutoProtoWatchedThread {/*_*/}
?>