<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2025-06-05 10:52:30                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoWatchedThreadDAO extends StorableDAO
	{
		protected $linkName =  'main';
		
		public function getTable()
		{
			return 'watched_thread';
		}
		
		public function getObjectName()
		{
			return 'WatchedThread';
		}
		
		public function getSequence()
		{
			return 'watched_thread_id';
		}
	}
?>