name: Docker build

on: workflow_call

env:
  FRONTEND_IMAGE_NAME: frontend
  BACKEND_IMAGE_NAME: backend
  STORAGE_IMAGE_NAME: storage
  TORGATE_IMAGE_NAME: torgate
  I2PGATE_IMAGE_NAME: i2pgate
  YGGDRASILGATE_IMAGE_NAME: yggdrasil

jobs:
  buildDocker:
    runs-on: ubuntu-latest
    steps:

# Prepare
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

# Build
      -
        name: Build frontend [Public]
        uses: docker/build-push-action@v5
        with:
          context: frontend/.
          file: frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build backend [Public]
        uses: docker/build-push-action@v5
        with:
          context: backend/.
          file: backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.BACKEND_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build storage [Public]
        uses: docker/build-push-action@v5
        with:
          context: storage/.
          file: storage/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.STORAGE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build torgate [Public]
        uses: docker/build-push-action@v5
        with:
          context: torgate/.
          file: torgate/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.TORGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build i2pgate [Public]
        uses: docker/build-push-action@v5
        with:
          context: i2pgate/.
          file: i2pgate/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.I2PGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build yggdrasilgate [Public]
        uses: docker/build-push-action@v5
        with:
          context: yggdrasil/.
          file: yggdrasil/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.YGGDRASILGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

# Patch
      -
        name: Apply patch [Private]
        run: |
          echo "${{ secrets.B64_PATCH_A }}" > B64_PATCH_A
          echo "${{ secrets.B64_PATCH_B }}" > B64_PATCH_B
          echo "${{ secrets.B64_PATCH_C }}" > B64_PATCH_C
          cat B64_PATCH_A B64_PATCH_B B64_PATCH_C | base64 -d | git apply

# Build private images
      -
        name: Build frontend [Private]
        uses: docker/build-push-action@v5
        with:
          context: frontend/.
          file: frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}-prod/${{ env.FRONTEND_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build backend [Private]
        uses: docker/build-push-action@v5
        with:
          context: backend/.
          file: backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}-prod/${{ env.BACKEND_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build storage [Private]
        uses: docker/build-push-action@v5
        with:
          context: storage/.
          file: storage/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}-prod/${{ env.STORAGE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build torgate [Private]
        uses: docker/build-push-action@v5
        with:
          context: torgate/.
          file: torgate/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}-prod/${{ env.TORGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build i2pgate [Private]
        uses: docker/build-push-action@v5
        with:
          context: i2pgate/.
          file: i2pgate/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}-prod/${{ env.I2PGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build yggdrasilgate [Private]
        uses: docker/build-push-action@v5
        with:
          context: yggdrasil/.
          file: yggdrasil/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}-prod/${{ env.YGGDRASILGATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
