<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2025-06-05 10:52:30                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class WatchedThread extends AutoWatchedThread implements Prototyped, DAOConnected
	{
		/**
		 * @return WatchedThread
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return WatchedThreadDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('WatchedThreadDAO');
		}
		
		/**
		 * @return ProtoWatchedThread
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoWatchedThread');
		}
		
		// your brilliant stuff goes here
	}
?>